services:
  - type: web
    name: calendly-automation-api
    runtime: python
    buildCommand: ./render-build.sh && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
